language: php

php:
 - 7.0

before_script:
    - composer install --prefer-dist
 - cp config.sample.json config.json

script: vendor/bin/phpunit --coverage-text  --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - haeuslmann@gmail.com
    on_success: never
    on_failure: always
